### ISSUE TITLE
TuBoleta.com fails credit card payments

### ISSUE THREAD

**Issue by matheo** [Ingenico-NPS-Latam/nps-sdk-php#3]
There's a huge bug pissing me off while trying to pay some tickets with my credit card at TuBoleta.com
it seems based in this software and the query is being made to `https://services2.nps.com.ar/ws.php` and the payment is refused.
Could you fix that stuff please? the logs throws enough warnings for this to be attended?
OMG

**Comment by IngenicoNPSLatam** [comment]
Hi,

Can you share the logs about this issue?

**Comment by matheo** [comment]
Not really, I'm not in charge of that platform, that's all what I see from the client side.
